services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopapp
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default

  backend-service:
    container_name: shopapp-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 3307
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: shopapp
      LOGSTASH_HOST: host.docker.internal:5600
    networks:
      - default

networks:
  default:
    name: shopapp-service

volumes:
  mysql_data: